### ISSUE TITLE
The locale can't be changed.

### ISSUE THREAD

**Issue by extremecat** [SBDPlugins/VehiclesPlus#111]
**Describe the bug**  
The locale can't be changed.

**To Reproduce**  
change config.yml locale: ru, Does not apply.
can't even add a new language, Editing "lang_en.yml" doesn't change the message.

**Server and Plugin Information**
 - VehiclesPlus Version: 2.3.0 Pro
 - Server Platform and Version: PaperSpigot** 1.16.3 #253
 - Operating System (if applicable): debian 10

**Comment by stijnb1234** [comment]
You have a file called lang_ru.yml?

And can you try disabing the server, then changing it and then start the server again?

**Comment by extremecat** [comment]
lang_ru.yml exists, Auto generated.
Doing so doesn't apply.

Editing an existing lang_en.yml doesn't apply.

**Comment by stijnb1234** [comment]
So, even if you change it when the server is stopped, it doesn't apply?

And the value in the config is still ru after the server started?

**Comment by extremecat** [comment]
that correct.
it's the value of ru even after restart.

**Comment by stijnb1234** [comment]
Send me the latest.log, which can be found in the folder logs.

**Comment by extremecat** [comment]
`[05:20:28 INFO]: ExtremeCat_ issued server command: /vp reload
[05:20:28 INFO]: Loaded: 42 vehicles!
[05:20:28 INFO]: Loaded: 1 rims!
[05:20:28 WARN]: java.lang.NullPointerException: Cannot invoke "me.legofreak107.vehiclesplus.vehicles.fuel.FuelType.getName()" because "<local4>" is null
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.vehicles.managers.VehicleManager.loadAllFuels(VehicleManager.java:130)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.vehicles.managers.VehicleManager.loadAll(VehicleManager.java:86)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.reload(VehiclesCommand.java:141)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:20:28 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BaseCommand.execute(BaseCommand.java:513)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.RootCommand.execute(RootCommand.java:99)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[05:20:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[05:20:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1333)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[05:20:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[05:20:28 WARN]: java.lang.NullPointerException: Cannot invoke "me.legofreak107.vehiclesplus.vehicles.fuel.FuelType.getName()" because "<local4>" is null
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.vehicles.managers.VehicleManager.loadAllFuels(VehicleManager.java:130)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.reload(VehiclesCommand.java:142)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[05:20:28 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:20:28 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BaseCommand.execute(BaseCommand.java:513)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.RootCommand.execute(RootCommand.java:99)
[05:20:28 WARN]:        at me.legofreak107.vehiclesplus.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[05:20:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[05:20:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1333)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[05:20:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[05:20:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[05:20:28 INFO]: Loaded: 1 rims!
`

**Comment by stijnb1234** [comment]
Send me the logs after startup. Not of /VP reload.

**Comment by extremecat** [comment]
[latest.log](https://github.com/SBDPlugins/VehiclesPlus/files/7124179/latest.log)

**Comment by stijnb1234** [comment]
Please provide me with your language file. It does not load because of an invalid yaml file.

**Comment by stijnb1234** [comment]
Got not response, closing this issue. If you still experience issues, do not bother to request reopening this issue.
